version: '3'

services:
  app:
    image: micro-videos-nestjs10-test_app:latest
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.prod
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - 3000:3000

  db_test:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos_test
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined

  redis:
    image: redis:7.0.8-alpine

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    tmpfs:
      - /var/lib/rabbitmq
